# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 511808694a74f922eb3f8bb35b7a68ad6f3f3261e5682e86cd4db36a0facd3d63306ba21fa8c8daa3de4b599479e46120862259b811e0896545216e78569736f

test:
  secret_key_base: 909f352b7c47614847a8bbfed6fd73d2338c875b322a8c379eb92672c13c43dafdc7137066acfdbb8cda74a10d8b057e76c9b0e39b7c272b9cb9022cc40b3110

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
